version: '3'
services:
  superset:
    build:
      context: .
      args:
        SUPERSET_VERSION: 0.28.1
    container_name: superset
    image: superset
    restart: always
    ports:
      - 8080:8088
    environment:
      - SUPERSET_HOME=/var/lib/superset/
      - GUNICORN_TIMEOUT=180
    volumes:
      - ${PWD}/config:/etc/superset/
      - ${PWD}/data:/var/lib/superset/
